services:

  task-management:
    build:
      context: ./.
      dockerfile: Dockerfile
    container_name: task-management
    hostname: task-management
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      host: "postgres"
      port: 5432
      db: "postgres"
      password: postgres
      user: postgres
    volumes:
      - /data/task-management/data:/var/lib/postgresql/data
    networks:
      - milsondev_network

  postgres:
    image: postgres:14.0
    container_name: postgres
    hostname: postgres
    volumes:
      - /data/task-management/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DBNAME: postgres
    ports:
      - 5432:5432
    networks:
      - milsondev_network

networks:
  milsondev_network:
    driver: bridge